const timezones = [
    { value: "America/Adak", label: "UTC-10:00 America/Adak" },
    { value: "America/Anchorage", label: "UTC-09:00 America/Anchorage" },
    { value: "America/Chicago", label: "UTC-06:00 America/Chicago" },
    { value: "America/Denver", label: "UTC-07:00 America/Denver" },
    { value: "America/Detroit", label: "UTC-05:00 America/Detroit" },
    { value: "America/Edmonton", label: "UTC-07:00 America/Edmonton" },
    { value: "America/Halifax", label: "UTC-04:00 America/Halifax" },
    { value: "America/Indianapolis", label: "UTC-05:00 America/Indianapolis" },
    { value: "America/Los_Angeles", label: "UTC-08:00 America/Los Angeles" },
    { value: "America/New_York", label: "UTC-05:00 America/New York" },
    { value: "America/Phoenix", label: "UTC-07:00 America/Phoenix" },
    { value: "America/St_Johns", label: "UTC-03:30 America/St Johns" },
    { value: "America/Toronto", label: "UTC-05:00 America/Toronto" },
    { value: "America/Vancouver", label: "UTC-08:00 America/Vancouver" },
    { value: "America/Winnipeg", label: "UTC-06:00 America/Winnipeg" },
    { value: "Asia/Jakarta", label: "UTC+07:00 Asia/Jakarta" },
    { value: "Asia/Jayapura", label: "UTC+09:00 Asia/Jayapura" },
    { value: "Asia/Karachi", label: "UTC+05:00 Asia/Karachi" },
    { value: "Asia/Kuala_Lumpur", label: "UTC+08:00 Asia/Kuala Lumpur" },
    { value: "Asia/Kuching", label: "UTC+08:00 Asia/Kuching" },
    { value: "Asia/Makassar", label: "UTC+08:00 Asia/Makassar" },
    { value: "Asia/Manila", label: "UTC+08:00 Asia/Manila" },
    { value: "Asia/Pontianak", label: "UTC+07:00 Asia/Pontianak" },
    { value: "Asia/Shanghai", label: "UTC+08:00 Asia/Shanghai" },
    { value: "Australia/Adelaide", label: "UTC+10:30 Australia/Adelaide" },
    { value: "Australia/Brisbane", label: "UTC+10:00 Australia/Brisbane" },
    { value: "Australia/Broken_Hill", label: "UTC+10:30 Australia/Broken Hill" },
    { value: "Australia/Darwin", label: "UTC+09:30 Australia/Darwin" },
    { value: "Australia/Eucla", label: "UTC+08:45 Australia/Eucla" },
    { value: "Australia/Hobart", label: "UTC+11:00 Australia/Hobart" },
    { value: "Australia/Lindeman", label: "UTC+10:00 Australia/Lindeman" },
    { value: "Australia/Lord_Howe", label: "UTC+11:00 Australia/Lord Howe" },
    { value: "Australia/Melbourne", label: "UTC+11:00 Australia/Melbourne" },
    { value: "Australia/Perth", label: "UTC+08:00 Australia/Perth" },
    { value: "Australia/Sydney", label: "UTC+11:00 Australia/Sydney" },
    { value: "Europe/Berlin", label: "UTC+01:00 Europe/Berlin" },
    { value: "Europe/Busingen", label: "UTC+01:00 Europe/Busingen" },
    { value: "Europe/London", label: "UTC+00:00 Europe/London" },
    { value: "Pacific/Honolulu", label: "UTC-10:00 Pacific/Honolulu" }
  ];
  
  export { timezones };
  